import * as xtermModule from '@xterm/xterm';
import * as fitModule from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
import * as monaco from 'monaco-editor';
import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
import jsonWorker from 'monaco-editor/esm/vs/language/json/json.worker?worker';
import cssWorker from 'monaco-editor/esm/vs/language/css/css.worker?worker';
import htmlWorker from 'monaco-editor/esm/vs/language/html/html.worker?worker';
import tsWorker from 'monaco-editor/esm/vs/language/typescript/ts.worker?worker';
import { InBrowserLinuxEngine } from './engine/LinuxEngine';
import { AssessmentRunner, type AssessmentResult } from './engine/AssessmentRunner';
import { StorageService } from './core/StorageService';
import { WorkspacePersistence } from './core/WorkspacePersistence';
(self as any).MonacoEnvironment={getWorker(_:any,label:string){if(label==='json')return new jsonWorker();if(label==='css'||label==='scss'||label==='less')return new cssWorker();if(label==='html'||label==='handlebars'||label==='razor')return new htmlWorker();if(label==='typescript'||label==='javascript')return new tsWorker();return new editorWorker();}};
const Terminal=(xtermModule as any).Terminal||(xtermModule as any).default?.Terminal||(xtermModule as any).default||xtermModule;const Fit=(fitModule as any).FitAddon||(fitModule as any).default?.FitAddon||(fitModule as any).default||fitModule;
class LinuxLabApp{
 private engine=new InBrowserLinuxEngine();private assessment=new AssessmentRunner(this.engine);private editor:monaco.editor.IStandaloneCodeEditor|null=null;private term:any;private fit:any;private file='main.c';private input='';private cursor=0;private history:string[]=[];private historyIndex=-1;private restoring=false;
 constructor(){requestAnimationFrame(async()=>{this.initTerm();this.initEditor();this.bind();await this.restore();});}
 private async restore(){this.restoring=true;try{const s=await WorkspacePersistence.load();if(s){WorkspacePersistence.restore(this.engine,s);this.file=s.currentFile||'main.c';this.history=[...this.engine.history].slice(-100);this.open(this.file);const p=await StorageService.getProgress(this.file.endsWith('.java')?'default-java':'default-c');if(p)this.showProgress(p);}}catch(e){console.warn('restore failed',e);}finally{this.restoring=false;this.prompt();}}
 private async persist(result?:AssessmentResult){if(this.restoring)return;try{await WorkspacePersistence.save(this.engine,this.file,result?{status:result.status,passed:result.passed,total:result.total,logs:result.logs}:undefined);}catch(e){console.warn('persist failed',e);}}
 private initEditor(){const c=document.getElementById('monaco-container');if(!c)return;this.editor=monaco.editor.create(c,{value:this.engine.readFile('/root/main.c')||'',language:'c',theme:'vs-dark',automaticLayout:true,fontSize:14,minimap:{enabled:false}});this.editor.onDidChangeModelContent(()=>{if(!this.restoring){this.engine.writeFile(`/root/${this.file}`,this.editor!.getValue());void this.persist();}});this.engine.setEditorHook((f,v)=>this.open(f,v));}
 private initTerm(){const c=document.getElementById('simulator-terminal-container');if(!c)return;this.term=new Terminal({cursorBlink:true,fontSize:14,fontFamily:'monospace',convertEol:true,rows:24,cols:80});this.fit=new Fit();this.term.loadAddon(this.fit);this.term.open(c);requestAnimationFrame(()=>this.fit.fit());this.term.writeln('\x1b[1;36mLinuxLab Interactive POSIX Shell\x1b[0m');this.term.writeln('Try: gcc main.c -o table && ./table');this.prompt();this.term.onData((d:string)=>this.inputData(d));}
 private prompt(){if(this.term)this.term.write(this.engine.getPrompt());}
 private redraw(){this.term.write('\x1b[2K\r'+this.engine.getPrompt()+this.input);const n=this.input.length-this.cursor;if(n>0)this.term.write(`\x1b[${n}D`);}
 private async submit(){this.term.write('\r\n');const cmd=this.input;this.input='';this.cursor=0;this.historyIndex=-1;if(cmd.trim()){this.history=this.history.filter(x=>x!==cmd.trim());this.history.unshift(cmd.trim());this.history=this.history.slice(0,100);const r=await this.engine.executeResult(cmd);if(r.stdout)this.term.writeln(r.stdout);if(r.stderr)this.term.writeln(`\x1b[31m${r.stderr}\x1b[0m`);await this.persist();}this.prompt();}
 private inputData(d:string){if(d==='\r'){void this.submit();return;}if(d==='\x1b[A'){if(this.history.length){this.historyIndex=Math.min(this.historyIndex+1,this.history.length-1);this.input=this.history[this.historyIndex];this.cursor=this.input.length;this.redraw();}return;}if(d==='\x1b[B'){this.historyIndex=this.historyIndex>0?this.historyIndex-1:-1;this.input=this.historyIndex>=0?this.history[this.historyIndex]:'';this.cursor=this.input.length;this.redraw();return;}if(d==='\x01'){this.cursor=0;this.redraw();return;}if(d==='\x05'){this.cursor=this.input.length;this.redraw();return;}if(d==='\x7f'||d==='\b'){if(this.cursor){this.input=this.input.slice(0,this.cursor-1)+this.input.slice(this.cursor);this.cursor--;this.redraw();}return;}if(d==='\x1b[D'){if(this.cursor){this.cursor--;this.term.write('\x1b[D');}return;}if(d==='\x1b[C'){if(this.cursor<this.input.length){this.cursor++;this.term.write('\x1b[C');}return;}if(d.length===1&&d>=' '){this.input=this.input.slice(0,this.cursor)+d+this.input.slice(this.cursor);this.cursor++;this.term.write(d);}}
 private open(f:string,v?:string){this.file=f;const content=v??this.engine.readFile(`/root/${f}`)??'';if(this.editor){const m=this.editor.getModel();if(m)monaco.editor.setModelLanguage(m,f.endsWith('.java')?'java':'c');if(this.editor.getValue()!==content)this.editor.setValue(content);}document.querySelectorAll('.file-tab').forEach(x=>x.classList.remove('active'));if(f==='main.c')document.getElementById('tab-main-c')?.classList.add('active');if(f==='Main.java')document.getElementById('tab-main-java')?.classList.add('active');if(!this.restoring)void this.persist();}
 private async save(){if(!this.editor)return;this.engine.writeFile(`/root/${this.file}`,this.editor.getValue());await this.persist();const e=document.getElementById('test-output-list');if(e)e.innerHTML=`<span style="color:#4ade80">✓ Workspace saved to IndexedDB.</span>`;}
 private showProgress(p:{score:number;passed:boolean;status?:string;logs?:string[]}){const e=document.getElementById('test-output-list');if(e)e.innerHTML=p.logs?.length?p.logs.join(''):`Restored: ${p.score} tests, ${p.status|| (p.passed?'passed':'failed')}.`;}
 private async grade(){if(!this.editor)return;await this.save();const r=this.file.endsWith('.java')?this.assessment.runJavaTestSuite(this.editor.getValue()):this.assessment.runCTestSuite(this.editor.getValue());const e=document.getElementById('test-output-list');if(e)e.innerHTML=r.logs.join('');await this.persist(r);}
 private async reset(){const fresh=new InBrowserLinuxEngine();this.engine.root=fresh.root;this.engine.cwdPath=[...fresh.cwdPath];this.engine.env=new Map(fresh.env);this.engine.history=[];this.history=[];this.historyIndex=-1;this.input='';this.cursor=0;this.file='main.c';await StorageService.clearWorkspace();this.open('main.c');this.term.clear();this.term.writeln('\x1b[33m[Virtual Environment Reset Complete]\x1b[0m');this.prompt();}
 private bind(){document.getElementById('tab-main-c')?.addEventListener('click',()=>this.open('main.c'));document.getElementById('tab-main-java')?.addEventListener('click',()=>this.open('Main.java'));document.getElementById('btn-save-fs')?.addEventListener('click',()=>void this.save());document.getElementById('btn-run-tests')?.addEventListener('click',()=>void this.grade());document.getElementById('btn-reset')?.addEventListener('click',()=>void this.reset());window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();void this.save();}});window.addEventListener('resize',()=>{this.editor?.layout();try{this.fit?.fit();}catch{}});}
}
window.addEventListener('DOMContentLoaded',()=>new LinuxLabApp());
